version: '2.0'
services:
  api:
    container_name: heroappbackend
    restart: always
    build: 
      context: .
      dockerfile: src/HeroApp.Api/Dockerfile
    ports:
      - "5000:80"

  wasm:
    container_name: heroappwasm
    build: 
        context: .
        dockerfile: src/HeroApp.Wasm/Dockerfile
    ports: 
      - "5502:80"
    depends_on:
      - api    
