CREATE TABLE IF NOT EXISTS migration_history (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK_migration_history" PRIMARY KEY ("MigrationId")
);

CREATE TABLE asp_net_roles (
    id text NOT NULL,
    name character varying(256) NULL,
    normalized_name character varying(256) NULL,
    concurrency_stamp text NULL,
    CONSTRAINT pk_asp_net_roles PRIMARY KEY (id)
);

CREATE TABLE asp_net_users (
    id text NOT NULL,
    user_name character varying(256) NULL,
    normalized_user_name character varying(256) NULL,
    email character varying(256) NULL,
    normalized_email character varying(256) NULL,
    email_confirmed boolean NOT NULL,
    password_hash text NULL,
    security_stamp text NULL,
    concurrency_stamp text NULL,
    phone_number text NULL,
    phone_number_confirmed boolean NOT NULL,
    two_factor_enabled boolean NOT NULL,
    lockout_end timestamp with time zone NULL,
    lockout_enabled boolean NOT NULL,
    access_failed_count integer NOT NULL,
    CONSTRAINT pk_asp_net_users PRIMARY KEY (id)
);

CREATE TABLE asp_net_role_claims (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    role_id text NOT NULL,
    claim_type text NULL,
    claim_value text NULL,
    CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_claims (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id text NOT NULL,
    claim_type text NULL,
    claim_value text NULL,
    CONSTRAINT pk_asp_net_user_claims PRIMARY KEY (id),
    CONSTRAINT fk_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_logins (
    login_provider text NOT NULL,
    provider_key text NOT NULL,
    provider_display_name text NULL,
    user_id text NOT NULL,
    CONSTRAINT pk_asp_net_user_logins PRIMARY KEY (login_provider, provider_key),
    CONSTRAINT fk_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_roles (
    user_id text NOT NULL,
    role_id text NOT NULL,
    CONSTRAINT pk_asp_net_user_roles PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE,
    CONSTRAINT fk_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE asp_net_user_tokens (
    user_id text NOT NULL,
    login_provider text NOT NULL,
    name text NOT NULL,
    value text NULL,
    CONSTRAINT pk_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name),
    CONSTRAINT fk_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
);

CREATE TABLE ongs (
    id text NOT NULL,
    name text NULL,
    email text NULL,
    whats_app text NULL,
    city text NULL,
    state text NULL,
    app_user_id text NULL,
    CONSTRAINT pk_ongs PRIMARY KEY (id),
    CONSTRAINT fk_ongs_asp_net_users_app_user_id FOREIGN KEY (app_user_id) REFERENCES asp_net_users (id) ON DELETE RESTRICT
);

CREATE TABLE incidents (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title text NULL,
    description text NULL,
    value text NULL,
    ong_id text NULL,
    CONSTRAINT pk_incidents PRIMARY KEY (id),
    CONSTRAINT fk_incidents_ongs_ong_id FOREIGN KEY (ong_id) REFERENCES ongs (id) ON DELETE RESTRICT
);

CREATE INDEX ix_asp_net_role_claims_role_id ON asp_net_role_claims (role_id);

CREATE UNIQUE INDEX role_name_index ON asp_net_roles (normalized_name);

CREATE INDEX ix_asp_net_user_claims_user_id ON asp_net_user_claims (user_id);

CREATE INDEX ix_asp_net_user_logins_user_id ON asp_net_user_logins (user_id);

CREATE INDEX ix_asp_net_user_roles_role_id ON asp_net_user_roles (role_id);

CREATE INDEX email_index ON asp_net_users (normalized_email);

CREATE UNIQUE INDEX user_name_index ON asp_net_users (normalized_user_name);

CREATE INDEX ix_incidents_ong_id ON incidents (ong_id);

CREATE INDEX ix_ongs_app_user_id ON ongs (app_user_id);

INSERT INTO migration_history ("MigrationId", "ProductVersion")
VALUES ('20200411151401_initial', '3.1.3');


